server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gsq?serverTimezone=GMT%2b8
    username: root
    password: gaoshiqi21
  redis:
    port: 6379
    host: 127.0.0.1
mybatis:
  mapper-locations: classpath:mapper/*.xml #扫描mapper下所有xml文件
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #显示日志sql(mybatis)
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
    path: D:/Download/files/
